### PR TITLE
Oracle RDS with HammerDB TPROC-C workload

### PR DESCRIPTION
**Pull request by mw2q**
Environment variables:

- TERRAFORM_PROJECT_PATH - Absolute path to the terraform project created by edb-terraform.
- TPROCC_DURATION - Duration in minutes execution.
- TPROCC_VUSERS - Number of virtual users.
- TPROCC_WAREHOUSE - Number of warehouses.
- BENCHMARK_NAME - string used to identify the target folder on the S3 bucket where data points and charts are pushed on.

### CODE REVIEW

**Comment by mw2q** [comment]
Need to make vusers configurable.

**Comment by mw2q** [comment]
Updated with input for setting vusers.

**Comment by mw2q** [comment]
Updated instance types with last force.

**Review by jt-edb — APPROVED** [review]
LGTM

**Comment by jt-edb** [comment]
@mw2q ready to be merged?

**Comment by mw2q** [comment]
Yeah, ready now. :)

**Pull request merged**
