### PR TITLE
Fix and update edb-benchmarks/aws-hammerdb-epas-oracle-compatibility

### PR DESCRIPTION
**Pull request by mw2q**
* The HammerDB patch needed to be updated
* Refactored the playbook to load the database more efficiently
* Added touchstone-tools for collection system and database stats

### CODE REVIEW

**Review by bryan-bar — CHANGES_REQUESTED** [review]
There is a merge conflict for provision/unprovision. 
Will need to pull the latest changes since we added the results directory and create terraform project path from terraform project name and the results directory path.

**Comment by mw2q** [comment]
> There is a merge conflict for provision/unprovision. Will need to pull the latest changes since we added the results directory and create terraform project path from terraform project name and the results directory path.

Ok, I think I cleaned it up and (mostly) tested it.

**Comment by mw2q** [comment]
Rebased and force push.

**Review by bryan-bar — APPROVED** [review]
LGTM

**Pull request merged**
